# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-VERPString
version:      0.01
version_from: lib/Crypt/VERPString.pm
installdirs:  site
requires:
    Crypt::Blowfish:               0
    Crypt::CBC:                    0
    MIME::Base32:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
